# Generated by Django 4.1.2 on 2022-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='patterns',
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
